executor: slurm
default-resources:
  - slurm_partition=c-frigon
  - mem_mb=60000
  - runtime=120
  - constraint=genoa
  - slurm_account=ctb-frigon_cpu
  - mpi=mpiexec
  - nodes=1
restart-times: 3
max-jobs-per-second: 10
max-status-checks-per-second: 1
latency-wait: 60
jobs: 10
keep-going: True
rerun-incomplete: True




