#Configuration file NAM-C3

custom:
    regions:
        southC3:
            name: southC3
            method: sel
            rlon: &rlon
              [-35, 28]
            rlat: [ -34, -12 ]
        middleC3:
            name: middleC3
            method: sel
            rlon: *rlon
            rlat:  [ -12, 7 ]
        northC3:
            name: northC3
            method: sel
            rlon: *rlon
            rlat: [ 7, 26 ]
    full_region:
      name:
        NAM-C3 #TODO: make sure you don't want CORDEX
      method: bbox
      tile_buffer: 1.5
      lon_bnds: [ -179.95, -10 ]
      lat_bnds: [ 16, 83.4 ]


extraction:
    reference:
        search_data_catalogs:
            variables_and_freqs:
                mask: fx
            periods : &ref_period
              - '1991'
              - '2020'            
            other_search_criteria:
                source:
                    "CaSR"
                version: "v31" #TODO: put 3.2 when available and change notes below as well
        extract_dataset:
            mask: True

biasadjust:
    variables:
        dtr: &generic-ba
            training_args:
                period: *ref_period
            # adjusting_args:
            #     bias_adjust_reference: #FIXME: put when xscen>=0.13.1
            #       CaSRv31 # TODO: put right version
        tasmax: *generic-ba
        pr: *generic-ba
        # hurs: *generic-ba #TODO: put back if not ESPO-R
        # hursTasmax: *generic-ba

bias_adjust_reference: #in the mean time
  CaSRv31


clean_up:
  xscen_clean_up:
      maybe_unstack_dict:
        rechunk:
          rlat: 20
          rlon: 20
          time: -1
      attrs_to_remove:
        rlat: original_shape
        rlon: original_shape
      add_attrs:
        global:
          Notes: |
            Regridded on the grid of CaSR v3.1, then bias-adjusted with detrended
            quantile mapping on a day-of-year basis with a window of 31 days, LOESS
            detrending and 50 quantiles. The reference was CaSR v3.1 over the
            1991-2020 period. Tasmax, hurs, hursTasmax, dtr and pr were adjusted, tasmin was computed
            from tasmax and dtr after the adjustment.
          code: https://github.com/Ouranosinc/ESPO-G/tree/snakemake
        rlat:
          axis: Y
        rlon:
          axis: X

diagnostics:
  properties_and_measures:
    period: *ref_period

health_checks:
    structure:
      coords:
        - rlat
        - rlon
        - time
        - lat 
        - lon
        - rotated_pole
      dims:
        - rlat
        - rlon
        - time
    

chunks:
  working:
    rlat: 20
    rlon: 20
    loc: 600
    time: -1
  diag:
    rlat: -1
    rlon: -1
  final: 
    rlat: 50
    rlon: 50
    time: 4year