#config_NAM-C3

full_region:
  name: NAM-C3
  method: bbox
  lon_bnds: [-179.95, -10  ]
  lat_bnds: [ 16, 83.4 ]

subregions: 
  n: 7500 # number of loc in one region
  num_of_regions: 37

extraction:
    reference:
        search_data_catalogs:
            variables_and_freqs: 
                mask: fx 
            other_search_criteria:
                source: 
                  CaSR
                version: "v31" #TODO: put 3.2 when available and change notes below as well
            periods : &ref_period
                  - '1991'
                  - '2020'
        extract_dataset:
             mask: True 


biasadjust_mbcn:
  train:
    period: *ref_period
  attrs:
    bias_adjust_project: MBCn-C3

clean_up:
  xscen_clean_up:
    attrs_to_remove:
      rlat: original_shape
      rlon: original_shape
    add_attrs:
      global:
        Notes: |
          Regridded on the grid of CaSR, then bias-adjusted with MBCn.
          The reference was CaSR over the 1991-2020 period.
      rlat:
        axis: Y
      rlon:
        axis: X
 
diagnostics:
  properties_and_measures:
    period: *ref_period
  health_checks:
    structure:
      coords:
        - lat
        - lon
        - rlat
        - rlon
        - rotated_pole
        - time
      dims:
        - rlat
        - rlon
        - time
  

chunks:
  working:
    rlat: 15
    rlon: 15
    loc: 10
    time: -1
  diag:
    rlat: -1
    rlon: -1
  final: 
    rlat: 30
    rlon: 30
    time: 4year