#Configuration file for ESPO-G6-E5L v1.0.0
project:
  name: ESPO-G6-E5L
  version: 1.0.0
  description: Ensemble de simulations post-traités d'Ouranos - Global - CMIP6
  id: eg6

custom:
    regions:
        south:
            name: south
            method: bbox
#            lon_bnds: [ -70,-60] # fake smaller region for testing
#            lat_bnds: [ 45, 47.05 ]
            lon_bnds: [ -179.95, -10 ]
            lat_bnds: [ 10, 40.05 ] # bound must land between 2 points
        middle:
            name: middle
            method: bbox
#            lon_bnds: [ -70,-60 ] # fake smaller region for testing
#            lat_bnds: [47.05, 49.05]
            lon_bnds: [ -179.95, -10 ]
            lat_bnds: [ 40.05, 65.05 ]
        north:
            name: north
            method: bbox
#            lon_bnds: [ -70,-60 ] # fake smaller region for testing
#            lat_bnds: [ 49.05, 53 ]
            lon_bnds: [-179.95, -10]
            lat_bnds: [65.05, 83.3] # changed from 83.4 to make it fit with other files
    amno_region:
      name: &nam-name
        NAM
      method: bbox
      tile_buffer: 1.5
#      lon_bnds: [ -70,-60 ] # fake smaller region for testing
#      lat_bnds: [ 45, 53 ]
      lon_bnds: [ -179.95, -10 ]
      lat_bnds: [ 10, 83.4 ]
    stack_drop_nans: &stack # goal is to drop Nan to make it faster
        True
    working_chunks:
        lat: 20
        lon: 20
        loc: 600
        time: -1
    final_chunks:
#        lat: 10 # for fake regions
#        lon: 10 # for fake regions
        lat: 50
        lon: 50
    ref_period : &ref_period
        - '1991'
        - '2020'
    sim_period: &sim_period
        - '1950'
        - '2100'
    maximal_calendar:
        noleap

extraction:
    reference:
        search_data_catalogs:
            variables_and_freqs: &var_and_freq
                tasmax: D
                tasmin: D
                pr: D
                dtr: D
            allow_resampling: False
            allow_conversion: True
            periods : *ref_period
            other_search_criteria:
                source: &ref_source
                    "ERA5-Land"
        extract_dataset:
            xr_combine_kwargs: {} # bc of xscen bug. Should be removed in the future
    simulation:
        search_data_catalogs:
            variables_and_freqs: *var_and_freq
            match_hist_and_fut: True
            allow_conversion: True
            allow_resampling: False
            restrict_members:
              ordered: 1
            periods: *sim_period
            other_search_criteria:
               processing_level: raw
               experiment:
                 - ssp585
               source:
                 - TaiESM1 # only do one model for testing
#                - CanESM5
#                - CNRM-CM6-1
#                - EC-Earth3-CC
#                - EC-Earth3
#                - EC-Earth3-Veg
#                - INM-CM4-8
#                - IPSL-CM6A-LR
#                - UKESM1-0-LL
#                - NorESM2-MM
#                - NESM3
        extract_dataset:
            periods : *sim_period
            xr_combine_kwargs:
              combine_attrs: override
            xr_open_kwargs:
              drop_variables:
                - height
        chunks: {'time': 365, 'lat':-1, 'lon':-1}
    ref_source: *ref_source

regrid:
  target:
    source: *ref_source
    calendar: noleap
  regrid_dataset:
      regridder_kwargs:
        method: bilinear
        extrap_method: inverse_dist
        locstream_out: *stack
        reuse_weights: False
      intermediate_grids:
        reg1:
          cf_grid_2d:
            lon0_b: 179.05
            lon1_b: 351.2
            d_lon: 1
            lat0_b: 9
            lat1_b: 84
            d_lat: 1
          regridder_kwargs:
            method: bilinear
            extrap_method: inverse_dist
            locstream_out: False
            reuse_weights: False
        reg2:
          cf_grid_2d:
            lon0_b: 179.04
            lon1_b: 351.2
            d_lon: 0.5
            lat0_b: 8.9
            lat1_b: 84
            d_lat: 0.5
          regridder_kwargs:
            method: bilinear
            extrap_method: inverse_dist
            locstream_out: False
            reuse_weights: False

biasadjust:
    variables:
        dtr:
            training_args:
                period: *ref_period
                method: DetrendedQuantileMapping
                group:
                    group: time.dayofyear
                    window: 31
                jitter_under: # to avoid negative dtr (when temperature inversion GFDL)
                   thresh: 1e-4 K
                xclim_train_args:
                    kind: "*"
                    nquantiles: 50
            adjusting_args:
                periods: *sim_period
                xclim_adjust_args:
                    detrend:
                        LoessDetrend:
                          f: 0.2
                          niter: 1
                          d: 0
                          weights: tricube
                    interp: nearest
                    extrapolation: constant
                bias_adjust_institution: &b_a_inst
                  Ouranos
                bias_adjust_project: &b_a_pro
                  ESPO-G6
        tasmax:
            training_args:
                period: *ref_period
                method: DetrendedQuantileMapping
                group:
                    group: time.dayofyear
                    window: 31
                xclim_train_args:
                    kind: "+"
                    nquantiles: 50
            adjusting_args:
                periods: *sim_period
                xclim_adjust_args:
                  detrend:
                    LoessDetrend:
                      f: 0.2
                      niter: 1
                      d: 0
                      weights: tricube
                  interp: nearest
                  extrapolation: constant
                bias_adjust_institution: *b_a_inst
                bias_adjust_project: *b_a_pro
        pr:
            training_args:
                period: *ref_period
                method: DetrendedQuantileMapping
                group:
                    group: time.dayofyear
                    window: 31
                adapt_freq:
                    thresh: 1 mm d-1
                jitter_under:
                    thresh: 0.01 mm d-1
                xclim_train_args:
                    kind: "*"
                    nquantiles: 50
            adjusting_args:
                periods: *sim_period
                xclim_adjust_args:
                  detrend:
                    LoessDetrend:
                      f: 0.2
                      niter: 1
                      d: 0
                      weights: tricube
                  interp: nearest
                  extrapolation: constant
                bias_adjust_institution: *b_a_inst
                bias_adjust_project: *b_a_pro

clean_up:
  search_data_catalogs:
    variables_and_freqs:
      tasmax: D
      tasmin: D
      pr: D
    allow_conversion: True
    allow_resampling: False
  problems:
    - CMIP6_ScenarioMIP_BCC_BCC-CSM2-MR_ssp245_r1i1p1f1_global
    - CMIP6_ScenarioMIP_BCC_BCC-CSM2-MR_ssp370_r1i1p1f1_global
    - CMIP6_ScenarioMIP_BCC_BCC-CSM2-MR_ssp585_r1i1p1f1_global
    - CMIP6_ScenarioMIP_NOAA-GFDL_GFDL-ESM4_ssp245_r1i1p1f1_global
    - CMIP6_ScenarioMIP_NOAA-GFDL_GFDL-ESM4_ssp370_r1i1p1f1_global
    - CMIP6_ScenarioMIP_NOAA-GFDL_GFDL-ESM4_ssp585_r1i1p1f1_global
  xscen_clean_up:
      maybe_unstack_dict:
        stack_drop_nans: *stack
        rechunk:
          lat: 20
          lon: 20
          time: -1
      round_var:
        pr: 10
      to_level: cleaned_up
      add_attrs:
        global:
          Notes: |
            Regridded on the grid of ERA5-Land, then bias-adjusted with detrended
            quantile mapping on a day-of-year basis with a window of 31 days, LOESS
            detrending and 50 quantiles. The reference was ERA5-Land over the
            1991-2020 period. Tasmax, dtr and pr were adjusted, tasmin was computed
            from tasmax and dtr after the adjustment.
          version: "1.0.0"
          code: https://github.com/Ouranosinc/ESPO-G/tree/snakemake
          contact: lavoie.juliette@ouranos.ca
          organisation: Groupe scénarios et services climatiques, Consortium Ouranos, Montréal, QC; www.ouranos.ca
          avertissement : Ouranos ne donne aucune garantie, expresse ou implicite, y compris, mais sans s'y limiter, les garanties de qualité marchande et d'adéquation à un usage particulier. Toutes les responsabilités découlant de la fourniture des informations (y compris toute responsabilité découlant d'une négligence) sont exclues dans toute la mesure permise par la loi.
          license:  Creative Commons Attribution 4.0 International (https://creativecommons.org/licenses/by/4.0/)
        lat:
          standard_name: latitude
          units: degrees_north
          axis: Y
          long_name: latitude
        lon:
          standard_name: longitude
          units: degrees_east
          axis: X
          long_name: longitude
        tasmax:
            standard_name: air_temperature
            long_name: Maximal daily temperature
            cell_methods: "time: maximum within days"
        tasmin:
            standard_name: air_temperature
            long_name: Minimal daily temperature
            cell_methods: "time: minimum within days"
        pr:
            standard_name: precipitation_flux
            long_name: Mean daily precipitation flux
            cell_methods: "time: mean within days"

health_checks:
    structure:
      coords:
        - lat
        - lon
        - time
      dims:
        - lat
        - lon
        - time
    start_date: "1950-01-01"
    end_date: "2100-12-30"
    variables_and_units:
      tasmax: "K"
      tasmin: "K"
      pr: "kg m-2 s-1"
    cfchecks:
      tasmax:
        cfcheck_from_name: {}
      tasmin:
        cfcheck_from_name: {}
      pr:
        cfcheck_from_name: {}
    freq: D
    flags:
      tasmax:
        temperature_extremely_high:
          thresh: '60 degC'
        tasmax_below_tasmin:
      tasmin:
        temperature_extremely_low:
          thresh: '-70 degC'
      pr:
        negative_accumulation_values:
        very_large_precipitation_events:
          thresh: '1650 mm/d'
    return_flags: True
    raise_on:
      - structure
      - start_date
      - end_date
      - variables_and_units
      - cfchecks
      - freq

off-diag:
  domains:
    Haudenosaunee:
        name: Haudenosaunee
        method: bbox
        lat_bnds: [ 42.0, 47.0 ]
        lon_bnds: [ -79.0, -71.0 ]
    Ute:
        name: Ute
        method: bbox
        lat_bnds: [ 35.0, 40.0 ]
        lon_bnds: [ -111.0, -103.0 ]
    Dene:
        name: Dene
        method: bbox
        lat_bnds: [ 60.0, 65.0 ]
        lon_bnds: [ -124.0, -116.0 ]
    Magtogoek:
      name: Magtogoek
      method: bbox
#      lat_bnds:  [ 48, 49] # small fake region
#      lon_bnds: [ -68, -62 ] # small fake region
      lat_bnds:  [ 41.4, 49.4]  #[ 41, 49]
      lon_bnds: [ -92.2, -59.8 ] #[ -92, -68 ]
  steps:
    ref:
      domain:
        Haudenosaunee: middle
        Ute: south
        Dene: middle
        Magtogoek: middle
      properties_and_measures:
        period: *ref_period
        properties: &off-properties
          config/off-properties_ESPO-G.yml
        to_level_prop: off-diag-ref-prop
      unstack: *stack
    sim:
      domain:
        Haudenosaunee: middle
        Ute: south
        Dene: middle
        Magtogoek: middle
      dref_for_measure:
        processing_level: off-diag-ref-prop
      properties_and_measures:
        period: *ref_period
        properties: *off-properties
        to_level_prop: off-diag-sim-prop
        to_level_meas: off-diag-sim-meas
      unstack: *stack
    scen:
      domain:
        Haudenosaunee: NAM
        Ute: NAM
        Dene: NAM
        Magtogoek: NAM
      dref_for_measure:
        processing_level: off-diag-ref-prop
      properties_and_measures:
        period: *ref_period
        properties: *off-properties
        to_level_prop: off-diag-scen-prop
        to_level_meas: off-diag-scen-meas
      unstack: False

io:
  rechunk:
    worker_mem: 2GB
  save_to_zarr:
    mode: o



logging:
    formatters:
        default:
            format: '%(asctime)s %(levelname)-8s %(name)-15s %(message)s'
            datefmt: '%Y-%m-%d %H:%M:%S'
    handlers:
        console:
            class : logging.StreamHandler
            formatter: default
            level : DEBUG
            stream: ext://sys.stdout #needed to have the right color in pycharm
    loggers:
        xscen:
            level: DEBUG
            handlers: [console]

dask:
    array.slicing.split_large_chunks: False

tdd:
  xarray_open_kwargs:
    decode_timedelta: False

