#Configuration file NAM-R2

custom:
    regions:
        south-rot:
            name: south-rot
            method: sel
            rlon: [ 324.5, 388.2 ]
            rlat: [ -47, -23 ]
        middle-rot:
            name: middle-rot
            method: sel
            rlon: [ 324.5, 388.2 ]
            rlat: [ -23, 1 ]
        north-rot:
            name: north-rot
            method: sel
            rlon: [ 324.5, 388.2 ]
            rlat: [ 1, 26 ]
    full_region:
      name: &nam-name
        NAM-R2
      method: bbox
      tile_buffer: 1.5
      lon_bnds: [ -179.95, -10 ]
      lat_bnds: [ 10, 83.4 ]


extraction:
    reference:
        search_data_catalogs:
            variables_and_freqs: &var_and_freq
                mask: fx 
            periods : &ref_period
              - '1989'
              - '2018'            
            other_search_criteria:
                source: &ref_source
                    "RDRS"
        extract_dataset:
            mask: True 

biasadjust:
    variables:
        dtr: &generic-ba
            training_args:
                period: *ref_period
            adjusting_args:
                bias_adjust_reference: 
                  RDRSv21
        tasmax: *generic-ba
        pr: *generic-ba
        hurs: *generic-ba
        hursTasmax: *generic-ba

clean_up:
  xscen_clean_up:
      maybe_unstack_dict:
        rechunk:
          rlat: 20
          rlon: 20
          time: -1
      attrs_to_remove:
        rlat: original_shape
        rlon: original_shape
      add_attrs:
        global:
          Notes: |
            Regridded on the grid of CaSR v2.1, then bias-adjusted with detrended
            quantile mapping on a day-of-year basis with a window of 31 days, LOESS
            detrending and 50 quantiles. The reference was CaSR v2.1 over the
            1989-2018 period. Tasmax, hurs, hursTasmax, dtr and pr were adjusted, tasmin was computed
            from tasmax and dtr after the adjustment.
          code: https://github.com/Ouranosinc/ESPO-G/tree/snakemake
        rlat:
          axis: Y
        rlon:
          axis: X

health_checks:
    structure:
      coords:
        - rlat
        - rlon
        - time
        - lat 
        - lon
        - rotated_pole
      dims:
        - rlat
        - rlon
        - time

diagnostics:
  properties_and_measures:
    period: *ref_period

chunks:
  working:
    rlat: 20
    rlon: 20
    loc: 600
    time: -1
  diag:
    rlat: -1
    rlon: -1
  final: 
    rlat: 50
    rlon: 50
    time: 4year