#Configuration file for ESPO-G6-E5L v1.0.0
paths:
  tmpdir: <SCRATCH-ESPO-DIR>
  home: <FULL-PATH-TO-THIS-REPO>
  final: <PROJECT-ESPO-DIR>

extraction:
    reference:
        search_data_catalogs:
            data_catalogs:
              - <PATH-TO-RECONSTRUCTION-CAT>
    simulation:
        search_data_catalogs:
            data_catalogs:
               - <PATH-TO-SIMULATION-CAT>



utils:
    stack_drop_nans:
        to_file: &coords
          <PROJECT-ESPO-DIR>coords/coords_{domain}_{shape}.nc
    unstack_fill_nan:
      coords: *coords
    maybe_unstack:
      coords: *coords
# for when we remove parse_config
clean_up:  
    xscen_clean_up:
      tasmax:
        maybe_unstack_dict:
          coords:  *coords
      tasmin:
        maybe_unstack_dict:
          coords:  *coords
      dtr:
        maybe_unstack_dict:
          coords:  *coords
      pr:
        maybe_unstack_dict:
          coords:  *coords

dask:
    client:
        dashboard_address: <YOUR-RANDOM-PORT-NUMBER>
        local_directory: <SCRATCH-ESPO-DIR>/dask/


#For create_hurstasmax
reccat: <PATH-TO-RECONSTRUCTION-CAT>
data: <PATH-TO-DATA>
espoinput: <PATH-TO-PERSONNAL-CAT>/ESPO-input.json
tmppath: <SCRATCH-TMP>