realm: generic
variables:
  hursTasmax:
    standard_name: relative_humidity
    description: Relative humidity at maximal daily temperature
    canonical_units: "%"
indicators:
  mean_tasmax:
    base: xsdba.properties.mean
    cf_attrs:
      long_name: mean maximum temperature
      standard_name: air_temperature
    input:
      da: tasmax
  q99_tasmax:
    base: xsdba.properties.quantile
    cf_attrs:
      long_name: 99th quantile of maximum temperature
      standard_name: air_temperature
    input:
      da: tasmax
    parameters:
      q: 0.99
  q01_tasmax:
    base: xsdba.properties.quantile
    cf_attrs:
      long_name: 1st quantile of maximum temperature
      standard_name: air_temperature
    input:
      da: tasmax
    parameters:
      q: 0.01
  aca_tasmax:
    base: xsdba.properties.annual_cycle_amplitude
    cf_attrs:
      long_name: Amplitude of the annual cycle of the maximum temperature
      standard_name: air_temperature
    input:
      da: tasmax
  aca_hurs:
    base: xsdba.properties.annual_cycle_amplitude
    input:
      da: hurs
  aca_hursTasmax:
    base: xsdba.properties.annual_cycle_amplitude
    input:
      da: hursTasmax
  corr_tasmax_hurs:
    base: xsdba.properties.corr_btw_var
    input:
      da1: tasmax
      da2: hurs
  corr_tasmax_hursTasmax:
    base: xsdba.properties.corr_btw_var
    input:
      da1: tasmax
      da2: hursTasmax
  mean_hurs:
    base: xsdba.properties.mean
    input:
      da: hurs
  q01_hurs:
    base: xsdba.properties.quantile
    input:
      da: hurs
    parameters:
      q: 0.01
  q99_hurs:
    base: xsdba.properties.quantile
    input:
      da: hurs
    parameters:
      q: 0.99
  mean_hursTasmax:
    base: xsdba.properties.mean
    input:
      da: hursTasmax
  q01_hursTasmax:
    base: xsdba.properties.quantile
    input:
      da: hursTasmax
    parameters:
      q: 0.01
  q99_hursTasmax:
    base: xsdba.properties.quantile
    input:
      da: hursTasmax
    parameters:
      q: 0.99