# Configuration file to compute diagnostics for  ESPO-G6-E5L v1.0.0 on the Hispaniola

# Some of the parameters are not needed for the computation of the diagnostics (e.g. extraction),
# but are needed for the workflow to run. They are defined as NO.

tasks:
  - official-diag


custom:
  regions:
    NO: NO
  stack_drop_nans: &stack
    True
  ref_period : &ref_period
    - '1991'
    - '2020'
  sim_period: &sim_period
    - '1950'
    - '2100'
  rechunk:
    lat: 50
    lon: 50


extraction:
  simulation:
    search_data_catalogs:
      variables_and_freqs:
        NO: D
  ref_source: &ref_source
    ERA5-Land


off-diag:
  domains:
    Hispaniola-E5L:
      name: Hispaniola-E5L
      method: bbox
      bbox:
        lon_bnds: [-75,-68]
        lat_bnds: [17.5,20.0]
  steps:
    ref:
      input:
        source: *ref_source
        calendar: default
        processing_level: extracted
      domain: &domains-off-diag
        Hispaniola-E5L: south_nodup
      properties_and_measures:
        period: *ref_period
      unstack: *stack
    sim:
      input:
        processing_level:  regridded
        experiment: ssp370
        source: &hausfather-source    # in the TCR likely range (14)
          - BCC-CSM2-MR
          - FGOALS-g3
          - CMCC-ESM2
          - CNRM-ESM2-1
          - ACCESS-CM2
          - ACCESS-ESM1-5
          - MPI-ESM1-2-HR
          - INM-CM5-0
          - MIROC6
          - MPI-ESM1-2-LR
          - MRI-ESM2-0
          - NorESM2-LM
          - KACE-1-0-G
          - GFDL-ESM4
      domain:
        Hispaniola-E5L: south
      dref_for_measure:
        processing_level: off-diag-ref-prop
      properties_and_measures:
        period: *ref_period
      unstack: *stack
    scen:
      input:
        processing_level: final
        experiment: ssp370
        source: *hausfather-source
      domain:
        Hispaniola-E5L: NAM
      dref_for_measure:
        processing_level: off-diag-ref-prop
      properties_and_measures:
        period: *ref_period
      unstack: False
  correlogram:
    regions: # list of region on which we want to calculate the correlogram
      - NO
    args:
      dims:
        - lat
        - lon


scripting:
    measure_time:
        cpu: True
    subject: ESPO-G6
    send_mail_on_exit:
        msg_ok: Toutes les étapes demandées ont été complétées.
        msg_err: Une erreur est survenue durant le traitement.
        on_error_only: True


dask:
    array.slicing.split_large_chunks: False


logging:
    formatters:
        default:
            format: '%(asctime)s %(levelname)-8s %(name)-15s %(message)s'
            datefmt: '%Y-%m-%d %H:%M:%S'
    handlers:
        console:
            class : logging.StreamHandler
            formatter: default
            level : INFO
        file:
            class: logging.FileHandler
            formatter: default
            level : DEBUG
    loggers:
        xscen:
            level: INFO
            handlers: [file]


tdd:
  xarray_open_kwargs:
    decode_timedelta: False
